apiVersion: v1
kind: Service
metadata:
  name: gamesystemservice-srv
spec:
  type: NodePort
  selector:
      app: gamesystemservice
  ports:
    - name: gamesystemservice
      protocol: TCP
      port: 80
      targetPort: 80
