apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamesystemservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamesystemservice
  template:
    metadata:
      labels:
        app: gamesystemservice
    spec:
      containers:
        - name: gamesystemservice
          image: nikunj3011/gamesystem
          imagePullPolicy: Never
